baseURL: "https://alterscopesolutions.com/"
languageCode: "en-us"
title: "Alterscope Solutions LLC"
theme: "ananke"
paginate: 20
params:
  ananke_socials:
    - name: github
      url: https://github.com/mattlandau
