baseURL: "https://alterscopesolutions.com/"
languageCode: "en-us"
title: "Alterscope Solutions LLC"
theme: "ananke"
paginate: 20

params:
  favicon: "favicon.ico"
  body_classes: "avenir bg-near-black"
  text_color: "white"
